import os
import sys
import time
import random
import logging
import re
import json
import requests
from openai import OpenAI

from wings.movie_facts import (
    SYSTEM_PROMPT as FACTS_SYSTEM,
    USER_PROMPT as FACTS_USER,
)
from wings.cinema_quiz import (
    SYSTEM_PROMPT as QUIZ_SYSTEM,
    USER_PROMPT as QUIZ_USER,
)
from wings.movie_recommendations import (
    SYSTEM_PROMPT as RECS_SYSTEM,
    USER_PROMPT as RECS_USER,
)

logging.basicConfig(
    level=logging.INFO,
    format="%(levelname)s | %(message)s",
)

BASE_URL = "https://openrouter.ai/api/v1"

# النموذج الأساسي
PRIMARY_MODEL = os.getenv(
    "OPENROUTER_MODEL",
    "openrouter/free",
)

# النموذج الاحتياطي والمراجع
FALLBACK_MODEL = os.getenv(
    "OPENROUTER_FALLBACK_MODEL",
    "meta-llama/llama-3.3-70b-instruct:free",
)

WINGS = [
    ("movie_facts", FACTS_SYSTEM, FACTS_USER),
    ("cinema_quiz", QUIZ_SYSTEM, QUIZ_USER),
    ("movie_recommendations", RECS_SYSTEM, RECS_USER),
]


def required_env(name):
    value = os.getenv(name)
    if not value:
        raise RuntimeError(f"Missing GitHub Secret: {name}")
    return value


def call_model(client, model, messages, temperature=0.5,
               max_tokens=1200):
    response = client.chat.completions.create(
        model=model,
        messages=messages,
        temperature=temperature,
        max_tokens=max_tokens,
    )

    if not response.choices:
        raise RuntimeError(f"{model}: no response choices")

    result = response.choices[0].message.content

    if not isinstance(result, str) or not result.strip():
        raise RuntimeError(f"{model}: empty response")

    return result.strip()


def build_prompt(user_prompt):
    return user_prompt + """

تعليمات تحريرية إلزامية:
- اكتب بعربية سليمة وطبيعية وسهلة الفهم.
- تجنب خلط الإنكليزية داخل الجمل العربية، إلا أسماء الأعمال الأصلية.
- اجعل المنشور جذاباً ومفيداً وليس مجرد كلام عام.
- استخدم عنواناً واضحاً وفقرات قصيرة ورموزاً تعبيرية باعتدال.
- لا تكرر الفكرة نفسها ولا تستخدم مقدمة طويلة بلا فائدة.
- لا تخترع معلومات أو أحداثاً أو جوائز أو تقييمات أو منصات عرض.
- إذا لم تكن متأكداً من معلومة، لا تعرضها كحقيقة.
- تجنب الحرق للأحداث.
- لا تستخدم تنسيق Markdown المعقد.
- أخرج نص المنشور فقط، دون شرح طريقة كتابته.
"""


def generate_draft(client, system_prompt, user_prompt):
    messages = [
        {"role": "system", "content": system_prompt},
        {"role": "user", "content": build_prompt(user_prompt)},
    ]

    # تجربة الأساسي ثم الاحتياطي عند فشل الطلب.
    models = list(dict.fromkeys([
        PRIMARY_MODEL,
        FALLBACK_MODEL,
    ]))

    errors = []

    for model in models:
        for attempt in range(1, 3):
            try:
                logging.info(
                    "Generating with %s, attempt %s",
                    model, attempt,
                )

                draft = call_model(
                    client,
                    model,
                    messages,
                    temperature=0.65,
                    max_tokens=1200,
                )

                logging.info("Draft generated by %s", model)
                return draft, model

            except Exception as exc:
                logging.warning(
                    "%s attempt %s failed: %s",
                    model, attempt, exc,
                )
                errors.append(f"{model}: {exc}")

                if attempt == 1:
                    time.sleep(2)

    raise RuntimeError(
        "All generation models failed: " + " | ".join(errors)
    )


def review_post(client, reviewer_model, system_prompt, draft):
    review_prompt = f"""
أنت محرر سينمائي مستقل ومحايد، مهمتك تدقيق منشور قبل نشره
في قناة تلغرام عربية.

قيّم المنشور من 10 وفق المعايير التالية:
1. الفائدة والأصالة: 3 درجات.
2. الدقة وعدم اختلاق المعلومات: 3 درجات.
3. سلامة العربية والوضوح: درجتان.
4. الجاذبية والتنظيم: درجتان.

كن صارماً ومحايداً. لا تمنح درجة عالية لمجرد أن النص مرتب.
الفكرة المكررة أو السطحية أو التي تحتوي معلومات مشكوكاً فيها
يجب أن تحصل على درجة أقل.

إذا كانت الدرجة أقل من 7:
- غيّر الفكرة أو زاوية المعالجة إذا كانت ضعيفة.
- حسّن المحتوى فعلياً، وليس الكلمات فقط.
- اجعل النص أكثر فائدة وتميزاً.
- صحح اللغة والتنسيق.
- لا تخترع حقائق أو تفاصيل غير مؤكدة.

إذا كانت الدرجة 7 أو أكثر:
- أبقِ الفكرة الجيدة.
- صحح أي مشكلة لغوية أو تحريرية واضحة.
- لا تغيّر المعلومات إلى معلومات غير موثوقة.

تعليمات نوع المنشور:
{system_prompt}

المنشور:
<POST>
{draft}
</POST>

أخرج JSON صالحاً فقط، دون Markdown، بالشكل التالي:
{{
  "score": 7.5,
  "reason": "سبب مختصر للدرجة",
  "revised_post": "النص النهائي المحسن"
}}

يجب أن تكون score رقماً بين 0 و10.
"""


    raw = call_model(
        client,
        reviewer_model,
        [
            {
                "role": "system",
                "content": (
                    "أنت مراجع محايد ودقيق. "
                    "أخرج JSON صالحاً فقط."
                ),
            },
            {"role": "user", "content": review_prompt},
        ],
        temperature=0.2,
        max_tokens=1600,
    )

    # التعامل مع احتمال وضع JSON داخل علامات تنسيق.
    match = re.search(r"\{.*\}", raw, re.DOTALL)

    if not match:
        raise RuntimeError("Reviewer did not return valid JSON")

    data = json.loads(match.group(0))
    score = float(data.get("score", -1))
    reason = str(data.get("reason", ""))
    revised_post = data.get("revised_post", "")

    if not 0 <= score <= 10:
        raise RuntimeError("Reviewer returned an invalid score")

    if not isinstance(revised_post, str) or not revised_post.strip():
        raise RuntimeError("Reviewer returned an empty final post")

    return score, reason, revised_post.strip()


def improve_post(client, system_prompt, draft, model):
    prompt = f"""
حسّن المنشور التالي تحسيناً حقيقياً قبل نشره.
حافظ على الدقة، ولا تخترع معلومات.
إذا كانت الفكرة سطحية أو مكررة، غيّر زاوية تناولها.
اكتب بعربية سليمة وطبيعية، واجعل المنشور مفيداً وجذاباً.
أخرج النسخة النهائية فقط.

تعليمات نوع المنشور:
{system_prompt}

المنشور الحالي:
{draft}
"""

    return call_model(
        client,
        model,
        [{"role": "user", "content": prompt}],
        temperature=0.4,
        max_tokens=1200,
    )


def generate_content(client, system_prompt, user_prompt):
    draft, generator_model = generate_draft(
        client,
        system_prompt,
        user_prompt,
    )

    # استخدم النموذج الآخر كمراجع إذا كان متاحاً.
    if generator_model == PRIMARY_MODEL:
        reviewer_model = FALLBACK_MODEL
    else:
        reviewer_model = PRIMARY_MODEL

    # مراجعتان كحد أقصى حتى لا يستهلك البوت الطلبات بلا نهاية.
    for round_number in range(1, 3):
        try:
            logging.info(
                "Quality review round %s using %s",
                round_number, reviewer_model,
            )

            score, reason, revised = review_post(
                client,
                reviewer_model,
                system_prompt,
                draft,
            )

            logging.info(
                "Quality score: %s/10. Reason: %s",
                score, reason[:250],
            )

            if score >= 7:
                logging.info("Post passed quality review.")
                return revised

            logging.warning(
                "Score below 7/10. Improving before publication."
            )

            draft = revised

        except Exception as exc:
            logging.warning(
                "Review with %s failed: %s",
                reviewer_model, exc,
            )

            # إذا تعطل المراجع، جرّب النموذج الذي أنشأ النص.
            if reviewer_model != generator_model:
                reviewer_model = generator_model
                continue

            # إذا تعذر التقييم، حاول تحسين النص مباشرة.
            try:
                draft = improve_post(
                    client,
                    system_prompt,
                    draft,
                    generator_model,
                )
            except Exception as improve_exc:
                logging.error(
                    "Improvement failed: %s",
                    improve_exc,
                )
                raise RuntimeError(
                    "Could not verify or improve post quality; "
                    "refusing to publish an unreviewed post."
                )

            # لا ننشر نصاً لم ينجح تدقيقه.
            raise RuntimeError(
                "Post improved, but quality review failed. "
                "No post was published; rerun the workflow."
            )

    # إذا بقي التقييم دون 7 بعد جولتي تحسين، لا تنشره.
    raise RuntimeError(
        "Post did not pass the 7/10 quality threshold. "
        "No post was published."
    )


def find_movie_image(message):
    patterns = [
        r"(?:العمل|الفيلم|المسلسل)\s*[:：-]\s*([^\n(]+?)(?:\s*\((\d{4})\))?\s*(?:\n|$)",
        r"\*\*([^*\n]+?)\s*\((\d{4})\)\*\*",
    ]

    title = None
    year = None

    for pattern in patterns:
        match = re.search(pattern, message, re.IGNORECASE)

        if match:
            title = match.group(1).strip(" *:-")

            if match.lastindex and match.lastindex >= 2:
                year = match.group(2)

            break

    if not title:
        logging.info("No movie title found for image search.")
        return None

    query = f"{title} film {year or ''}".strip()

    try:
        response = requests.get(
            "https://en.wikipedia.org/w/api.php",
            params={
                "action": "query",
                "generator": "search",
                "gsrsearch": query,
                "gsrnamespace": 0,
                "gsrlimit": 5,
                "prop": "pageimages",
                "piprop": "thumbnail",
                "pithumbsize": 900,
                "format": "json",
            },
            headers={"User-Agent": "FilmFilesXBot/1.0"},
            timeout=15,
        )

        response.raise_for_status()

        pages = response.json().get("query", {}).get("pages", {})
        candidates = list(pages.values())

        candidates.sort(
            key=lambda page: (
                title.lower() not in page.get("title", "").lower()
            )
        )

        for page in candidates:
            image_url = page.get("thumbnail", {}).get("source")

            if image_url and image_url.startswith("https://"):
                logging.info(
                    "Found image from Wikipedia: %s",
                    page.get("title"),
                )
                return image_url

    except (requests.RequestException, ValueError) as exc:
        logging.warning("Image search failed: %s", exc)

    logging.info("No image found; publishing text only.")
    return None


def send_telegram(bot_token, chat_id, message, image_url=None):
    if image_url:
        endpoint = (
            f"https://api.telegram.org/bot{bot_token}/sendPhoto"
        )
        payload = {
            "chat_id": chat_id,
            "photo": image_url,
            "caption": message[:1024],
        }
    else:
        endpoint = (
            f"https://api.telegram.org/bot{bot_token}/sendMessage"
        )
        payload = {
            "chat_id": chat_id,
            "text": message,
        }

    for attempt in range(1, 4):
        try:
            response = requests.post(
                endpoint,
                json=payload,
                timeout=45,
            )

            try:
                result = response.json()
            except ValueError:
                result = {}

            if response.ok and result.get("ok"):
                logging.info("Telegram post sent successfully.")
                return

            logging.error(
                "Telegram HTTP %s: %s",
                response.status_code,
                response.text[:500],
            )

            # إذا رفض تلغرام الصورة، جرّب النص وحده.
            if image_url and response.status_code == 400:
                logging.warning(
                    "Photo rejected; retrying as text."
                )
                return send_telegram(
                    bot_token,
                    chat_id,
                    message,
                )

        except requests.RequestException as exc:
            logging.warning(
                "Telegram attempt %s failed: %s",
                attempt, exc,
            )

        if attempt < 3:
            time.sleep(attempt * 2)

    raise RuntimeError("Failed to send post to Telegram.")


def main():
    api_key = required_env("OPENROUTER_API_KEY")
    bot_token = required_env("TELEGRAM_BOT_TOKEN")
    chat_id = required_env("TELEGRAM_CHAT_ID")

    client = OpenAI(
        api_key=api_key,
        base_url=BASE_URL,
        default_headers={
            "HTTP-Referer": "https://github.com/mad477382-prog/tele",
            "X-Title": "FilmFilesX Auto Publisher",
        },
    )

    selected_wing = os.getenv("WING")

    if selected_wing:
        selected = [
            wing for wing in WINGS
            if wing[0] == selected_wing
        ]

        if not selected:
            raise RuntimeError(
                f"Unknown WING: {selected_wing}"
            )
    else:
        selected = [random.choice(WINGS)]

    for name, system_prompt, user_prompt in selected:
        logging.info("Selected content type: %s", name)

        content = generate_content(
            client,
            system_prompt,
            user_prompt,
        )

        image_url = None

        if name == "movie_recommendations":
            image_url = find_movie_image(content)

        send_telegram(
            bot_token,
            chat_id,
            content,
            image_url,
        )


if __name__ == "__main__":
    try:
        main()
    except Exception:
        logging.exception("FilmFilesX failed")
        sys.exit(1)
