import os
import sys
import time
import random
import logging
import re
import json
import requests
from openai import OpenAI

from wings.movie_facts import (
    SYSTEM_PROMPT as FACTS_SYSTEM,
    USER_PROMPT as FACTS_USER,
)
from wings.cinema_quiz import (
    SYSTEM_PROMPT as QUIZ_SYSTEM,
    USER_PROMPT as QUIZ_USER,
)
from wings.movie_recommendations import (
    SYSTEM_PROMPT as RECS_SYSTEM,
    USER_PROMPT as RECS_USER,
)

logging.basicConfig(
    level=logging.INFO,
    format="%(levelname)s | %(message)s",
)

BASE_URL = "https://openrouter.ai/api/v1"

PRIMARY_MODEL = os.getenv(
    "OPENROUTER_MODEL",
    "openrouter/free",
)

FALLBACK_MODEL = os.getenv(
    "OPENROUTER_FALLBACK_MODEL",
    "google/gemma-3-27b-it:free",
)

MIN_SCORE = 7.0
MAX_REVIEW_ROUNDS = 3

WINGS = [
    ("movie_facts", FACTS_SYSTEM, FACTS_USER),
    ("cinema_quiz", QUIZ_SYSTEM, QUIZ_USER),
    ("movie_recommendations", RECS_SYSTEM, RECS_USER),
]


def required_env(name):
    value = os.getenv(name)
    if not value:
        raise RuntimeError(f"Missing GitHub Secret: {name}")
    return value


def call_model(
    client,
    model,
    messages,
    temperature=0.5,
    max_tokens=1200,
):
    response = client.chat.completions.create(
        model=model,
        messages=messages,
        temperature=temperature,
        max_tokens=max_tokens,
    )

    if not response.choices:
        raise RuntimeError(f"{model}: no response choices")

    result = response.choices[0].message.content

    if not isinstance(result, str) or not result.strip():
        raise RuntimeError(f"{model}: empty response")

    return result.strip()


def build_prompt(user_prompt):
    return user_prompt + """

تعليمات تحريرية إلزامية:
- اكتب بعربية سليمة وطبيعية وسهلة الفهم.
- تجنب خلط الإنكليزية داخل الجمل العربية، عدا أسماء الأعمال.
- اجعل المنشور مفيداً ومميزاً وليس كلاماً عاماً.
- استخدم عنواناً واضحاً وفقرات قصيرة.
- استخدم الرموز التعبيرية باعتدال.
- لا تكرر الفكرة ولا تطل المقدمة بلا فائدة.
- لا تخترع معلومات أو جوائز أو تقييمات أو تواريخ.
- لا تذكر معلومات مشكوكاً فيها وكأنها حقائق.
- تجنب حرق الأحداث والنهايات.
- أخرج نص المنشور فقط.
"""


def generate_draft(client, system_prompt, user_prompt):
    messages = [
        {"role": "system", "content": system_prompt},
        {"role": "user", "content": build_prompt(user_prompt)},
    ]

    models = list(dict.fromkeys([
        PRIMARY_MODEL,
        FALLBACK_MODEL,
    ]))

    errors = []

    for model in models:
        try:
            logging.info("Generating with %s", model)

            draft = call_model(
                client,
                model,
                messages,
                temperature=0.65,
                max_tokens=1200,
            )

            logging.info("Draft generated by %s", model)
            return draft, model

        except Exception as exc:
            logging.warning(
                "Generation with %s failed: %s",
                model,
                str(exc)[:300],
            )
            errors.append(f"{model}: {exc}")

    raise RuntimeError(
        "All generation models failed: " + " | ".join(errors)
    )


def review_post(client, reviewer_model, system_prompt, draft):
    review_prompt = f"""
أنت محرر سينمائي مستقل ومحايد. دقق المنشور قبل نشره
في قناة تلغرام عربية.

قيّم من 10 وفق المعايير:
1. الفائدة والأصالة: 3 درجات.
2. الدقة وعدم اختلاق المعلومات: 3 درجات.
3. سلامة العربية والوضوح: درجتان.
4. الجاذبية والتنظيم: درجتان.

كن صارماً. لا تمنح درجة عالية لنص سطحي أو قصير جداً
أو مكرر أو يحتوي على معلومات غير موثوقة.

إذا كانت الدرجة أقل من 7:
- حسّن النص فعلياً، وليس الكلمات فقط.
- غيّر زاوية الفكرة إذا كانت ضعيفة أو مكررة.
- صحح اللغة والأخطاء والمعلومات المشكوك فيها.
- اجعل النص مفيداً وجذاباً ومناسباً لنوع المنشور.
- لا تخترع حقائق لتجعل المنشور يبدو أفضل.

تعليمات نوع المنشور:
{system_prompt}

النص المطلوب تقييمه:
<POST>
{draft}
</POST>

أخرج JSON صالحاً فقط، بالشكل التالي:
{{
  "score": 8,
  "reason": "سبب مختصر وواضح",
  "revised_post": "النص المحسن كاملاً"
}}

score رقم بين 0 و10.
revised_post يجب أن يحتوي النص كاملاً.
"""

    raw = call_model(
        client,
        reviewer_model,
        [
            {
                "role": "system",
                "content": (
                    "أنت مراجع مستقل وصارم. "
                    "أخرج JSON صالحاً فقط."
                ),
            },
            {"role": "user", "content": review_prompt},
        ],
        temperature=0.2,
        max_tokens=1600,
    )

    match = re.search(r"\{.*\}", raw, re.DOTALL)

    if not match:
        raise RuntimeError("Reviewer did not return valid JSON")

    data = json.loads(match.group(0))

    score = float(data.get("score", -1))
    reason = str(data.get("reason", ""))
    revised = data.get("revised_post", "")

    if not 0 <= score <= 10:
        raise RuntimeError("Reviewer returned an invalid score")

    if not isinstance(revised, str) or not revised.strip():
        raise RuntimeError("Reviewer returned an empty post")

    return score, reason, revised.strip()


def improve_post(client, system_prompt, draft, model):
    prompt = f"""
أنت محرر سينمائي محترف.

أعد كتابة المنشور التالي لتحسين فائدته وأصالته ووضوحه.
إذا كانت الفكرة ضعيفة أو مكررة، غيّر زاوية المعالجة.
اكتب عربية سليمة، بعناوين وفقرات قصيرة.
لا تخترع معلومات أو تواريخ أو جوائز أو تقييمات.
التزم بتعليمات نوع المنشور أدناه.
أخرج نص المنشور النهائي فقط.

تعليمات نوع المنشور:
{system_prompt}

المنشور الذي يحتاج إلى تحسين:
{draft}
"""

    return call_model(
        client,
        model,
        [{"role": "user", "content": prompt}],
        temperature=0.45,
        max_tokens=1400,
    )


def generate_content(client, system_prompt, user_prompt):
    draft, generator_model = generate_draft(
        client,
        system_prompt,
        user_prompt,
    )

    other_model = (
        FALLBACK_MODEL
        if generator_model == PRIMARY_MODEL
        else PRIMARY_MODEL
    )

    reviewer_model = other_model
    models_to_try = list(dict.fromkeys([
        reviewer_model,
        generator_model,
    ]))

    last_score = None

    for round_number in range(1, MAX_REVIEW_ROUNDS + 1):
        logging.info(
            "Quality review round %s/%s using %s",
            round_number,
            MAX_REVIEW_ROUNDS,
            reviewer_model,
        )

        review_succeeded = False
        review_errors = []

        # جرّب المراجع الآخر أولاً، ثم نموذج التوليد عند الفشل.
        for model in models_to_try:
            try:
                score, reason, revised = review_post(
                    client,
                    model,
                    system_prompt,
                    draft,
                )

                reviewer_model = model
                review_succeeded = True
                last_score = score

                logging.info(
                    "Quality score: %.1f/10. Reason: %s",
                    score,
                    reason[:250],
                )

                if score >= MIN_SCORE:
                    logging.info(
                        "Post passed quality review. Ready to publish."
                    )
                    return revised

                logging.warning(
                    "Score below %.1f. Improving before publication.",
                    MIN_SCORE,
                )

                # نستخدم النسخة المحسنة ونقيّمها من جديد بالجولة التالية.
                draft = revised
                break

            except Exception as exc:
                logging.warning(
                    "Review with %s failed: %s",
                    model,
                    str(exc)[:300],
                )
                review_errors.append(f"{model}: {exc}")

        if not review_succeeded:
            raise RuntimeError(
                "Could not complete quality review. "
                "No post was published. "
                + " | ".join(review_errors)
            )

        # إذا كانت هذه آخر جولة، لا ننشر منشوراً لم يحقق الدرجة.
        if round_number >= MAX_REVIEW_ROUNDS:
            break

        # نحسّن المنشور قبل إعادة تقييمه.
        try:
            draft = improve_post(
                client,
                system_prompt,
                draft,
                generator_model,
            )
            logging.info("Improvement completed; next review will verify it.")

        except Exception as exc:
            logging.warning(
                "Improvement with %s failed: %s",
                generator_model,
                str(exc)[:300],
            )

            # جرّب نموذجاً آخر للتحسين.
            alternative = (
                FALLBACK_MODEL
                if generator_model == PRIMARY_MODEL
                else PRIMARY_MODEL
            )

            try:
                draft = improve_post(
                    client,
                    system_prompt,
                    draft,
                    alternative,
                )
                logging.info(
                    "Improvement completed with %s",
                    alternative,
                )
            except Exception as second_exc:
                raise RuntimeError(
                    "Could not improve the post. No post was published. "
                    f"Last score: {last_score}. "
                    f"Errors: {exc}; {second_exc}"
                )

    raise RuntimeError(
        "Post did not pass the 7/10 quality threshold after "
        f"{MAX_REVIEW_ROUNDS} review rounds. "
        f"Last score: {last_score}. No post was published."
    )


def find_movie_image(message):
    patterns = [
        r"(?:العمل|الفيلم|المسلسل)\s*[:：-]\s*([^\n(]+?)(?:\s*\((\d{4})\))?\s*(?:\n|$)",
        r"\*\*([^*\n]+?)\s*\((\d{4})\)\*\*",
    ]

    title = None
    year = None

    for pattern in patterns:
        match = re.search(pattern, message, re.IGNORECASE)

        if match:
            title = match.group(1).strip(" *:-")

            if match.lastindex and match.lastindex >= 2:
                year = match.group(2)

            break

    if not title:
        logging.info("No movie title found for image search.")
        return None

    query = f"{title} film {year or ''}".strip()

    try:
        response = requests.get(
            "https://en.wikipedia.org/w/api.php",
            params={
                "action": "query",
                "generator": "search",
                "gsrsearch": query,
                "gsrnamespace": 0,
                "gsrlimit": 5,
                "prop": "pageimages",
                "piprop": "thumbnail",
                "pithumbsize": 900,
                "format": "json",
            },
            headers={"User-Agent": "FilmFilesXBot/1.0"},
            timeout=12,
        )

        response.raise_for_status()

        pages = response.json().get("query", {}).get("pages", {})
        candidates = list(pages.values())

        candidates.sort(
            key=lambda page: (
                title.lower() not in page.get("title", "").lower()
            )
        )

        for page in candidates:
            image_url = page.get("thumbnail", {}).get("source")

            if image_url and image_url.startswith("https://"):
                logging.info(
                    "Found image from Wikipedia: %s",
                    page.get("title"),
                )
                return image_url

    except (requests.RequestException, ValueError) as exc:
        logging.warning("Image search failed: %s", exc)

    logging.info("No image found; publishing text only.")
    return None


def send_telegram(bot_token, chat_id, message, image_url=None):
    if image_url:
        endpoint = (
            f"https://api.telegram.org/bot{bot_token}/sendPhoto"
        )
        payload = {
            "chat_id": chat_id,
            "photo": image_url,
            "caption": message[:1024],
        }
    else:
        endpoint = (
            f"https://api.telegram.org/bot{bot_token}/sendMessage"
        )
        payload = {
            "chat_id": chat_id,
            "text": message,
        }

    for attempt in range(1, 4):
        try:
            response = requests.post(
                endpoint,
                json=payload,
                timeout=25,
            )

            try:
                result = response.json()
            except ValueError:
                result = {}

            if response.ok and result.get("ok"):
                logging.info("Telegram post sent successfully.")
                return

            logging.error(
                "Telegram HTTP %s: %s",
                response.status_code,
                response.text[:500],
            )

            # إذا رفض تيليغرام الصورة، أرسل النص وحده.
            if image_url and response.status_code == 400:
                logging.warning(
                    "Photo rejected; retrying as text."
                )
                return send_telegram(
                    bot_token,
                    chat_id,
                    message,
                )

        except requests.RequestException as exc:
            logging.warning(
                "Telegram attempt %s failed: %s",
                attempt,
                str(exc)[:300],
            )

        if attempt < 3:
            time.sleep(attempt * 2)

    raise RuntimeError("Failed to send post to Telegram.")


def main():
    api_key = required_env("OPENROUTER_API_KEY")
    bot_token = required_env("TELEGRAM_BOT_TOKEN")
    chat_id = required_env("TELEGRAM_CHAT_ID")

    # مهلة محددة ومنع إعادة المحاولة الداخلية الطويلة من المكتبة.
    client = OpenAI(
        api_key=api_key,
        base_url=BASE_URL,
        timeout=25.0,
        max_retries=0,
        default_headers={
            "HTTP-Referer": "https://github.com/mad477382-prog/tele",
            "X-Title": "FilmFilesX Auto Publisher",
        },
    )

    selected_wing = os.getenv("WING")

    if selected_wing:
        selected = [
            wing for wing in WINGS
            if wing[0] == selected_wing
        ]

        if not selected:
            raise RuntimeError(f"Unknown WING: {selected_wing}")
    else:
        selected = [random.choice(WINGS)]

    for name, system_prompt, user_prompt in selected:
        logging.info("Selected content type: %s", name)

        content = generate_content(
            client,
            system_prompt,
            user_prompt,
        )

        image_url = None

        if name == "movie_recommendations":
            image_url = find_movie_image(content)

        send_telegram(
            bot_token,
            chat_id,
            content,
            image_url,
        )


if __name__ == "__main__":
    try:
        main()
    except Exception:
        logging.exception("FilmFilesX failed")
        sys.exit(1)
